# Base image
FROM node:16-alpine

# Working directory
WORKDIR '/app'

# Install dependencies
COPY ./package.json ./
RUN npm install

# Copy everything
COPY . .

# Default command
CMD ["npm", "run", "start"]