sudo: required
services:
    - docker
before_install:
    # Use the encrypted version stored on Travis and decrypt it
    - openssl aes-256-cbc -K $encrypted_9f3b5599b056_key -iv $encrypted_9f3b5599b056_iv -in service-account.json.enc -out service-account.json -d

    # Install Google Cloud SDK CLI
    - curl https://sdk.cloud.google.com | bash > /dev/null;
    - source $HOME/google-cloud-sdk/path.bash.inc
    # Install and update kubectl in the Travis environment
    - gcloud components update kubectl

    # Configure the SDK with our Google Cloud auth info using service-account.json file
    - gcloud auth activate-service-account --key-file service-account.json

    -
    # Login to Docker CLI

    # Build the 'test' version of multi-client
    # Run tests

    # if tests are successful, run a script to deploy newest images

    # Build all our images, tag each one, push each to docker hub
    # Apply all configs in the 'k8s' folder

    # Imperatively set latest images on each deployment
