apiVersion: apps/v1
kind: Deployment
metadata:
    name: server-deployment
spec:
    replicas: 3
    selector:
        matchLabels:
            component: server
    template:
        metadata:
            labels:
                component: server
        spec:
            containers:
                - name: server
                  image: rawanad/multi-server
                  ports:
                      - containerPort: 5000
                  # Environment variables for the databases
                  env:
                      # redis host will be the Redis ClusterIP service
                      - name: REDIS_HOST
                        value: redis-cluster-ip-service
                      - name: REDIS_PORT
                        value: '6379'
                      - name: PGUSER
                        value: postgres
                        # postgres host will be the Postgres ClusterIP service
                      - name: PGHOST
                        value: postgres-cluster-ip-service
                      - name: PGPORT
                        value: '5432'
                      - name: PGDATABASE
                        value: postgres
                        # Secret
                      - name: PGPASSWORD
                        valueFrom:
                            secretKeyRef:
                                # secret name
                                name: pgpassword
                                # key inside the secret
                                key: PGPASSWORD
